AXION_COMMON_PATH := device/axion/common
AXION_COMMON_MODULE_ROOT := $(AXION_COMMON_PATH)/kernel/modules
AXION_COMMON_KERNEL_MODULES := \
    ax_thread_snooper \
    ax_affinity_guard \
    ax_boost \
    ax_atcm \
    ax_game_boost \
    ax_frame_boost \
    ax_burst_sched \
    ax_binder_ux

ifneq ($(strip $(TARGET_KERNEL_SOURCE)),)
ifeq ($(strip $(TARGET_PREBUILT_KERNEL)),)
ifneq ($(wildcard $(TARGET_KERNEL_SOURCE)/Makefile),)
AXION_COMMON_KERNEL_VERSION := $(shell awk \
    '/^VERSION =/{version=$$3} /^PATCHLEVEL =/{patch=$$3} END{if (version && patch) print version "." patch}' \
    $(TARGET_KERNEL_SOURCE)/Makefile)
AXION_COMMON_KERNEL_MAJOR := $(firstword $(subst ., ,$(AXION_COMMON_KERNEL_VERSION)))
AXION_KERNEL_MODULES_BINDER_UX_HOOKS ?= y
AXION_KERNEL_MODULES_BINDER_OBS_HOOKS ?= y
AXION_KERNEL_MODULES_SCHED_RQ_HOOKS ?= y
AXION_KERNEL_MODULES_SCHED_NOCHECK ?= y
AXION_KERNEL_MODULES_TASK_TRACEPOINTS ?= y
AXION_KERNEL_MODULES_AFFINITY_GUARD_HOOK ?= y
AXION_KERNEL_MODULES_UCLAMP_EFF_HOOK ?= $(if $(filter 6,$(AXION_COMMON_KERNEL_MAJOR)),y,n)
AXION_KERNEL_MODULES_MAP_UTIL_FREQ_HOOK ?= y
AXION_KERNEL_MODULES_AX_BOOST ?= y
AXION_KERNEL_MODULES_ATCM ?= y
AXION_KERNEL_MODULES_GAME_BOOST ?= y
AXION_KERNEL_MODULES_AX_BOOST_GPU_PROVIDER ?= y
AXION_KERNEL_MODULES_AX_BOOST_MEMLAT_PROVIDER ?= y
AXION_KERNEL_MODULES_AX_BOOST_DDR_PROVIDER ?= y
AXION_KERNEL_MODULES_AX_BOOST_L3_PROVIDER ?= y

TARGET_KERNEL_ADDITIONAL_FLAGS += \
    AXION_KERNEL_MODULES_BINDER_UX_HOOKS=$(AXION_KERNEL_MODULES_BINDER_UX_HOOKS) \
    AXION_KERNEL_MODULES_BINDER_OBS_HOOKS=$(AXION_KERNEL_MODULES_BINDER_OBS_HOOKS) \
    AXION_KERNEL_MODULES_SCHED_RQ_HOOKS=$(AXION_KERNEL_MODULES_SCHED_RQ_HOOKS) \
    AXION_KERNEL_MODULES_SCHED_NOCHECK=$(AXION_KERNEL_MODULES_SCHED_NOCHECK) \
    AXION_KERNEL_MODULES_TASK_TRACEPOINTS=$(AXION_KERNEL_MODULES_TASK_TRACEPOINTS) \
    AXION_KERNEL_MODULES_AFFINITY_GUARD_HOOK=$(AXION_KERNEL_MODULES_AFFINITY_GUARD_HOOK) \
    AXION_KERNEL_MODULES_UCLAMP_EFF_HOOK=$(AXION_KERNEL_MODULES_UCLAMP_EFF_HOOK) \
    AXION_KERNEL_MODULES_MAP_UTIL_FREQ_HOOK=$(AXION_KERNEL_MODULES_MAP_UTIL_FREQ_HOOK) \
    AXION_KERNEL_MODULES_AX_BOOST=$(AXION_KERNEL_MODULES_AX_BOOST) \
    AXION_KERNEL_MODULES_ATCM=$(AXION_KERNEL_MODULES_ATCM) \
    AXION_KERNEL_MODULES_GAME_BOOST=$(AXION_KERNEL_MODULES_GAME_BOOST) \
    AXION_KERNEL_MODULES_AX_BOOST_GPU_PROVIDER=$(AXION_KERNEL_MODULES_AX_BOOST_GPU_PROVIDER) \
    AXION_KERNEL_MODULES_AX_BOOST_MEMLAT_PROVIDER=$(AXION_KERNEL_MODULES_AX_BOOST_MEMLAT_PROVIDER) \
    AXION_KERNEL_MODULES_AX_BOOST_DDR_PROVIDER=$(AXION_KERNEL_MODULES_AX_BOOST_DDR_PROVIDER) \
    AXION_KERNEL_MODULES_AX_BOOST_L3_PROVIDER=$(AXION_KERNEL_MODULES_AX_BOOST_L3_PROVIDER)

ifeq ($(strip $(TARGET_KERNEL_EXT_MODULE_ROOT)),)
TARGET_KERNEL_EXT_MODULE_ROOT := $(AXION_COMMON_MODULE_ROOT)
endif

ifeq ($(TARGET_KERNEL_EXT_MODULE_ROOT),$(AXION_COMMON_MODULE_ROOT))
TARGET_KERNEL_EXT_MODULES += $(foreach module,$(AXION_COMMON_KERNEL_MODULES),$(module):kbuild)
endif
endif
endif
endif
